# Generated by Django 4.1.1 on 2022-10-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
