# Generated by Django 4.1.1 on 2022-09-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0002_item_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.CharField(
                default="https://images.pexels.com/photos/4439444/pexels-photo-4439444.jpeg?auto=compress&cs=tinysrgb&w=800",
                max_length=800,
            ),
        ),
    ]
