# Generated by Django 4.1.1 on 2022-10-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
