# Generated by Django 4.1.1 on 2022-10-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0006_comment_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="Item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="food.item",
            ),
        ),
    ]
