# Generated by Django 4.1.1 on 2022-10-10 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food", "0007_alter_comment_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="likes",
            field=models.ManyToManyField(
                related_name="item_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
