# Generated by Django 4.1.1 on 2022-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food", "0008_item_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_image",
            field=models.ImageField(blank=True, null=True, upload_to="item_pictures"),
        ),
    ]
